"""DocEngine — Application Service: ValidationService.

Validates extraction results for quality issues and generates
actionable warnings. This service does NOT raise exceptions —
it only annotates the result with warnings.
"""

from __future__ import annotations

from app.config.settings import AppSettings
from app.domain.models.document import ExtractionResult
from app.domain.models.extraction import ExtractionStatus
from app.infrastructure.logging.logger import get_logger

logger = get_logger(__name__)

# Quality thresholds
_MIN_CHARS_PER_PAGE = 100          # Expected minimum characters per page
_MIN_HEADING_RATIO = 0.0001        # At least 1 heading per 10,000 chars
_MAX_TABLE_EMPTY_RATIO = 0.5       # Warn if >50% of table lines are empty


class ValidationService:
    """Validates extraction results and generates quality warnings.

    All validation checks are non-blocking: they add entries to
    result.metadata.warnings without altering status or content.

    Args:
        config: Application settings (currently unused, reserved for future).
    """

    def __init__(self, config: AppSettings) -> None:
        self._config = config

    def validate_result(self, result: ExtractionResult) -> list[str]:
        """Run all validation checks against an extraction result.

        Appends warnings directly to result.metadata.warnings and also
        returns them for convenient inspection in tests.

        Args:
            result: The extraction result to validate.

        Returns:
            List of warning strings generated by all checks.
        """
        warnings: list[str] = []

        if result.status == ExtractionStatus.FAILED:
            warnings.append("WARN:001 Extraction failed — no content to validate.")
            result.metadata.warnings.extend(warnings)
            return warnings

        warnings.extend(self._check_empty_markdown(result))
        warnings.extend(self._check_content_density(result))
        warnings.extend(self._check_heading_presence(result))
        warnings.extend(self._check_table_quality(result))
        warnings.extend(self._check_error_presence(result))

        if warnings:
            logger.warning(
                "Validation warnings found",
                document_id=result.document_id,
                filename=result.metadata.filename,
                warning_count=len(warnings),
            )

        result.metadata.warnings.extend(warnings)
        return warnings

    # ------------------------------------------------------------------
    # Private check methods
    # ------------------------------------------------------------------

    def _check_empty_markdown(self, result: ExtractionResult) -> list[str]:
        """Warn if the Markdown output is empty or near-empty.

        Args:
            result: Extraction result to check.

        Returns:
            List with warning string, or empty list if check passes.
        """
        warnings = []
        if not result.markdown.strip():
            warnings.append(
                "WARN:010 Markdown output is empty. "
                "The PDF may be scanned/image-based and requires OCR (Phase 2)."
            )
        elif len(result.markdown.strip()) < 50:
            warnings.append(
                f"WARN:011 Markdown output is very short ({len(result.markdown)} chars). "
                "Content may be incomplete."
            )
        return warnings

    def _check_content_density(self, result: ExtractionResult) -> list[str]:
        """Warn if character-per-page ratio is unusually low.

        Args:
            result: Extraction result to check.

        Returns:
            List with warning string, or empty list if check passes.
        """
        warnings = []
        page_count = result.metadata.page_count

        if page_count > 0:
            chars_per_page = len(result.markdown) / page_count
            if chars_per_page < _MIN_CHARS_PER_PAGE:
                warnings.append(
                    f"WARN:020 Low content density: {chars_per_page:.0f} chars/page "
                    f"(expected ≥{_MIN_CHARS_PER_PAGE}). "
                    "Pages may be image-based or have minimal text."
                )
        return warnings

    def _check_heading_presence(self, result: ExtractionResult) -> list[str]:
        """Warn if no headings are detected in a substantial document.

        Args:
            result: Extraction result to check.

        Returns:
            List with warning string, or empty list if check passes.
        """
        warnings = []
        md = result.markdown
        heading_count = md.count("\n#")

        if len(md) > 1000 and heading_count == 0:
            warnings.append(
                "WARN:030 No Markdown headings (##) detected in a substantial document. "
                "Document structure may not have been correctly identified."
            )
        return warnings

    def _check_table_quality(self, result: ExtractionResult) -> list[str]:
        """Warn if tables appear malformed in the Markdown output.

        Args:
            result: Extraction result to check.

        Returns:
            List with warning strings, or empty list if check passes.
        """
        warnings = []

        if result.metadata.tables_detected == 0:
            return warnings

        # Count table rows vs separator rows
        table_lines = [
            line
            for line in result.markdown.splitlines()
            if line.startswith("|")
        ]
        separator_lines = [line for line in table_lines if set(line.replace("|", "").replace("-", "").replace(":", "").strip()) == set()]

        if table_lines:
            separator_ratio = len(separator_lines) / len(table_lines)
            if separator_ratio > _MAX_TABLE_EMPTY_RATIO:
                warnings.append(
                    f"WARN:040 High ratio of table separator lines "
                    f"({separator_ratio:.0%}). Tables may be malformed."
                )

        return warnings

    def _check_error_presence(self, result: ExtractionResult) -> list[str]:
        """Warn if the extraction result carries error messages.

        Args:
            result: Extraction result to check.

        Returns:
            List with warning strings for each error.
        """
        warnings = []
        for error in result.metadata.errors:
            warnings.append(f"WARN:050 Extraction error recorded: {error}")
        return warnings
