"""DocEngine — Infrastructure: PostgreSQL Vector Search Repository.

Read-only repository for similarity search against the policy_chunks table
using pgvector's cosine distance operator (<=>).

This module performs NO write operations and does NOT import or interfere
with PgRagRepository or any ingestion-side logic.
"""

from __future__ import annotations

from typing import Any

from app.domain.models.query_models import RetrievedChunk
from app.infrastructure.database.db_connection import DatabaseManager
from app.infrastructure.logging.logger import get_logger

logger = get_logger(__name__)

# Cosine similarity = 1 - cosine_distance (pgvector uses distance, not similarity)
# score = 1 - (embedding <=> query_vector)
_SIMILARITY_QUERY_BASE = """
    SELECT
        pc.id                                          AS chunk_id,
        pc.policy_id::text                             AS policy_id,
        pc.chunk_index                                 AS chunk_index,
        pc.chunk_content                               AS chunk_content,
        pc.metadata_json                               AS metadata_json,
        (1 - (pc.embedding <=> %s::vector))            AS similarity_score
    FROM policy_chunks pc
    {where_clause}
    ORDER BY similarity_score DESC
    LIMIT %s;
"""


class PgVectorSearchRepository:
    """Read-only repository for vector similarity search in policy_chunks.

    Uses pgvector's cosine distance operator (<=>). All queries are SELECT-only;
    this class cannot mutate any data in the database.

    The similarity score is computed as:
        score = 1 - cosine_distance(chunk_embedding, query_embedding)

    A score of 1.0 means identical vectors; 0.0 means orthogonal (unrelated).
    """

    def __init__(self, db_manager: DatabaseManager) -> None:
        self._db = db_manager

    def search_similar_chunks(
        self,
        query_vector: list[float],
        top_k: int = 5,
        similarity_threshold: float = 0.3,
        filters: dict[str, Any] | None = None,
    ) -> list[RetrievedChunk]:
        """Retrieve the top-K most similar chunks for a given query vector.

        The search executes in two steps:
        1. Pre-filter by metadata (policy_id / company_sigla) if filters provided.
        2. Rank by cosine similarity and return only chunks above the threshold.

        Args:
            query_vector: Dense 1024-dimensional embedding of the user query.
                Must have been generated by the same model used during ingestion
                (BAAI/bge-m3) to ensure vector space compatibility.
            top_k: Maximum number of chunks to return (default 5, max 20).
            similarity_threshold: Minimum cosine similarity score to include a
                chunk in the result (default 0.3). Chunks below this score are
                discarded regardless of ranking.
            filters: Optional dict for pre-filtering. Supported keys:
                - "policy_id" (str): Filter to a specific policy UUID.
                - "company_sigla" (str): Filter to a specific insurance company.
                  Joined via the policies table.

        Returns:
            List of RetrievedChunk instances ordered by similarity_score DESC.
            Returns an empty list if no chunks meet the threshold.

        Raises:
            psycopg2.DatabaseError: On connection or query failure.
        """
        top_k = min(max(1, top_k), 20)  # Clamp to [1, 20]

        where_clauses: list[str] = []
        params: list[Any] = []

        # Always inject query vector as first parameter (for the <=> operator)
        vector_str = _vector_to_pg_str(query_vector)

        # Build optional pre-filter WHERE clauses
        needs_policy_join = False

        if filters:
            if "policy_id" in filters and filters["policy_id"]:
                where_clauses.append("pc.policy_id = %s::uuid")
                params.append(filters["policy_id"])

            if "company_sigla" in filters and filters["company_sigla"]:
                # Requires a join to the policies table for sigla filtering
                needs_policy_join = True
                where_clauses.append("p.company_sigla = UPPER(%s)")
                params.append(filters["company_sigla"])

        # Build the final query
        if needs_policy_join:
            join_clause = "JOIN policies p ON pc.policy_id = p.id"
            query_template = _SIMILARITY_QUERY_BASE.replace(
                "FROM policy_chunks pc",
                f"FROM policy_chunks pc {join_clause}",
            )
        else:
            query_template = _SIMILARITY_QUERY_BASE

        where_clause = f"WHERE {' AND '.join(where_clauses)}" if where_clauses else ""
        sql = query_template.format(where_clause=where_clause)

        # Final params: [vector_str, ...filter_params, top_k]
        final_params = [vector_str] + params + [top_k]

        logger.debug(
            "Executing vector similarity search",
            top_k=top_k,
            threshold=similarity_threshold,
            filters=filters,
        )

        results: list[RetrievedChunk] = []

        with self._db.get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(sql, final_params)
                rows = cur.fetchall()

        for row in rows:
            chunk_id, policy_id, chunk_index, chunk_content, metadata_json, similarity_score = row

            # Apply similarity threshold post-query for clarity
            # (pgvector index scans return top-k by distance; threshold narrows further)
            if similarity_score < similarity_threshold:
                logger.debug(
                    "Chunk below similarity threshold — discarded",
                    chunk_id=chunk_id,
                    score=round(similarity_score, 4),
                    threshold=similarity_threshold,
                )
                continue

            results.append(
                RetrievedChunk(
                    chunk_id=chunk_id,
                    policy_id=str(policy_id),
                    chunk_index=chunk_index,
                    chunk_content=chunk_content,
                    metadata_json=metadata_json if isinstance(metadata_json, dict) else {},
                    similarity_score=float(similarity_score),
                )
            )

        logger.info(
            "Vector similarity search completed",
            total_rows=len(rows),
            chunks_above_threshold=len(results),
            threshold=similarity_threshold,
        )

        return results


# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------


def _vector_to_pg_str(vector: list[float]) -> str:
    """Convert a Python float list to a pgvector-compatible string literal.

    PostgreSQL pgvector expects the format: '[0.1, 0.2, ..., 0.n]'

    Args:
        vector: List of floats representing the embedding.

    Returns:
        String in pgvector format: '[f1, f2, ..., fn]'.
    """
    return "[" + ",".join(str(v) for v in vector) + "]"
